version: '3.6'

# App Services
services:
  fe-react-app:
    build:
      dockerfile: Dockerfile
    image: node:16.19.0-alpine
    container_name: fe-react-app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/home/react/apps
    networks:
      - frontend

networks:
  frontend:
    driver: 'bridge'